### ISSUE TITLE
Weird gap at the top of the screen when dismissing the BottomSheet

### ISSUE THREAD

**Issue by AvgustPol** [the49code/The49.Maui.BottomSheet#10]
Description:

I came across an issue when using the BottomSheet in my project. When I try to dismiss the full-screen BottomSheet, there is a weird gap at the top of the screen. I suspect that there might be some bugs, or perhaps I'm doing something wrong.

I was able to observe that the sample app provided in the repository does not have this issue, and the BottomSheet works beautifully in the sample app.

![image](https://user-images.githubusercontent.com/29002229/229856356-ed9e5518-b876-4fe4-8402-b174d9c5a4e3.png)
Steps to reproduce:

Implement a full-screen BottomSheet in a project.
Dismiss the BottomSheet.
Observe the weird gap at the top of the screen.
Expected behavior:

The BottomSheet should dismiss without any weird gap at the top of the screen, similar to the sample app provided in the repository.

Actual behavior:

When dismissing the full-screen BottomSheet, a weird gap appears at the top of the screen.

Additional context:

Here's a link to a video where I encountered the issue (timestamped to the relevant part): https://www.youtube.com/watch?v=JJUm58avADo&t=755s

[![JJUm58avADo](https://img.youtube.com/vi/JJUm58avADo/0.jpg)](https://www.youtube.com/watch?v=JJUm58avADo)

I would appreciate any guidance on how to resolve this issue, or please let me know if there are any known bugs or workarounds.

Thank you!

**Comment by paulvarache** [comment]
Hi,

Could you provide the following information:
Did you set IsModal to true or false?
When can you see the gap appearing? During the sheet opening animation? Can you see the gap if you drag the sheet down? Or does it appear after the sheet finishes its closing animation?

I'll be trying to replicate on my side, but the more details I get from you the better.

The gap seems roughly the same height as the statusBar, so I wonder if that has something to do with that. Note that this issue might not be there on Android 12 and up (it seems your emulator runs Android 10).

**Comment by AvgustPol** [comment]
## It helped! 😊
Changing adding `page.IsModal = true;` to my solution helped to avoid this issue ! 

## Thanks a lot <3 
You definitely should update documentation to make it more clear that adding this line will help to fix the issue with gap. And I`m not the first person, who encountered this issue 

## Did you set IsModal to true or false?
I didn't set page.IsModal to any value, so it was `default`, which is FALSE (I assume) 

## OS systems: 
Android 13 

## Additional information 

This is how my final code looks like 
```
var page = new DataPickerBottomSheetPage();
page.IsModal = true;
page.ShowHandle = true;
page.Cancelable = true;

page.Show(Window);
```

**Comment by AvgustPol** [comment]
## 🎥 Video reproduction of the bug: 
@paulvarache you asked: 
> When can you see the gap appearing? During the sheet opening animation? Can you see the gap if you drag the sheet down? Or does it appear after the sheet finishes its closing animation?

I'm adding url to youtube video with EXACT time code of bug reproducing: 
https://www.youtube.com/watch?v=JJUm58avADo&t=755s

_This means when you'll open the YouTube video you'll open it in the exact moment you need to watch_

**Comment by paulvarache** [comment]
Ok, great. Didn't realise it was in the video itself.

This is definitely something I'd like to fix over making people use the IsModal=true workaround.

I think I have a good idea of what's happening then, I'll try to get a fix in

**Comment by AvgustPol** [comment]
@paulvarache that's awesome ! <3 

Looking forward for future patch :3 

P.s. yeah, I assumed you missed the link, so I duplicated it - hope it will give you some clearness of what happened 

P.s.s. I don't even know if you`re aware that @jfversluis made a video about your tool but I share his opinion that your project looks worth "Amazing Plugin Alert" and as a content creator I assume this is something you should know 🥰

**Comment by paulvarache** [comment]
Hi,

I have cloned the repo from the video and with the latest version, the gap doesn't appear

**Comment by jfversluis** [comment]
Thanks for this @paulvarache !
