### ISSUE TITLE
🐞 App crash after reopening BottomSheet modal 😱🥺

### ISSUE THREAD

**Issue by AvgustPol** [the49code/The49.Maui.BottomSheet#11]
Hey there, amazing 49ers! 🤠👋

I hope you're having a fantastic day! 😃 I've stumbled upon a 🐛 that's causing our app to crash, and I could really use your expertise to squash it. 🙏

# Steps to reproduce the issue 🕵️‍♀️:

1) Create a button that, when clicked, opens the BottomSheet modal with the following code:
```
var page = new DataPickerBottomSheetPage();
page.IsModal = true;
page.ShowHandle = true;
page.Cancelable = true;
page.Show(Window);
```
2) Click on the button 🖱️ and behold the modal in all its glory! 🌟
3) Dismiss the BottomSheet modal by pulling it down like a fancy window blind 📉
4) Click on the same button again to reopen the modal 🔄
💥 Boom! The app goes down like a house of cards 🃏🏠

## Expected behavior 🧐:
The app should allow us to open and close the BottomSheet modal as many times as our hearts desire, without any crashes. 😍🔄

## Actual behavior 😵:
The app crashes when we try to reopen the BottomSheet modal after dismissing it. 😢💔

Environment 🌍:

| Specification              | Details                    |
|----------------------------|----------------------------|
| Device Model               | Android Emulator - Pixel 5 |
| Operating System           | Android 13                 |
| BottomSheet Version        | 1.0.0-alpha4               |

I know you folks are wizards when it comes to fixing bugs like these! 🧙‍♂️ So, I'm sure this issue will be resolved in no time. Thanks in advance for your help! You're the best! 😎🎉

Keep up the fantastic work, and may the force be with you! 🚀🌟

**Comment by paulvarache** [comment]
This seems similar to #9
Can you check what the stack trace says to see if it mentions a ratio being between 0 and 1?

**Comment by AvgustPol** [comment]
@paulvarache this is the exact error I`m facing right now: 

```
Java.Lang.IllegalArgumentException
  Message=ratio must be a float value between 0 and 1
```

I`m going to create a separate project sample, reproduce the error there and provide you repo with detailed stack trace

**Comment by paulvarache** [comment]
Yes please, I tried to replicate but couldn't using the sample app

**Comment by AntonVlasiuk** [comment]
@paulvarache I`ve successfully located the source of this issue - `detents` 🤯🤭🤭🤭

Please take a closer look: 
https://github.com/AntonVlasiuk/BottomSheetIssueSample 


https://github.com/AntonVlasiuk/BottomSheetIssueSample/commit/914f5489809816a5b79fd98320b19ab429453a1c
![image](https://user-images.githubusercontent.com/129162078/230054067-64d10638-15b2-4e9a-9beb-c21ec9316d0f.png)


FYI: I`ve used company account to publish sample it, don't be surprised seeing same account with different name

**Comment by paulvarache** [comment]
I have isolated the issue and will try to get a fix for it. In the meantime, a workaround is to use the `DetentsCollection`:

Replace
```xaml
    <the49:BottomSheet.Detents>
        <the49:FullscreenDetent />
    </the49:BottomSheet.Detents>
```

With

```xaml
<the49:BottomSheet.Detents>
        <the49:DetentsCollection>
            <the49:FullscreenDetent />
        </the49:DetentsCollection>
    </the49:BottomSheet.Detents>
```

And the problem goes away. Alternatively setting the Detents programmatically in the Code-Behind will also fix this issue

**Comment by AvgustPol** [comment]
@paulvarache thank you for an instant reply! 💖

The issue with your workaround is that if you`ll provide only FullscreenDenent - it locks the view on the Fullscreen size and you can't change that.

Adding one more 'detent' I  works perfectly for me: 
```
    <the49:BottomSheet.Detents>
        <the49:DetentsCollection>
            <the49:RatioDetent Ratio="0.45" />
            <the49:FullscreenDetent />
        </the49:DetentsCollection>
    </the49:BottomSheet.Detents>
```

In this example BottomSheet opens on 45% f the screen and than you can change it to full screen by pulling to the top. 
Awesome <3 

![yay](https://media.giphy.com/media/z8XtwKGIRQSBCmU4sW/giphy-downsized.gif)

**Comment by paulvarache** [comment]
When no detent is provided, a `ContentDetent` is used. It calculates the height of the content in the sheet to snap at. When providing your own detents, it overrides that default. To get the original behaviour AND the full screen detent, you can use:

```xml
<the49:BottomSheet.Detents>
        <the49:DetentsCollection>
            <the49:FullscreenDetent />
            <the49:ContentDetent />
        </the49:DetentsCollection>
    </the49:BottomSheet.Detents>
```

**Comment by paulvarache** [comment]
Hi,

1.0.0-alpha6 was just published and it removes the need to use `DetentsCollection`. It also fixes this issue
