### ISSUE TITLE
Maui.BottomSheet crashes when it is called from different view pages and viewmodels.

### ISSUE THREAD

**Issue by dg2k** [the49code/The49.Maui.BottomSheet#16]
I tracked the issue down to `_frame` being `null` in  `public void Layout()` which is located in Platforms\Android\BottomSheetController.cs code file.

- Download the demo project from https://github.com/dg2k/MauiBottomSheetFailDemo
- Run it in the same way as the sample  project that accompanies the Maui.BottomSheet package.
- The project starts with a Home Page. Tap on the top right toolbar icon to invoke a demo. BottomSheet shows up with two buttons, one to navigate to a HelpPage and the other for Dismiss action. Try out Dismiss first and again tap on toolbar this time to navigate to HelpPage.
- On the Help Page, like for the previous page, tap on the toolbar icon to invoke Maui.BottomSheet. When this attempt is made,  it fails because the _frame object being `null`.
- I made it break on `Debug.Assert(_frame is not null);` and commenting this out will show the obvious error.
- PR #17 seems to solve the problem -- just uncommented a line that was commented out the issue is gone for my usage scenario.

**Comment by dg2k** [comment]
Thank you very Paul for the speedy action. My code is already up to date one rarely comes across such a turnaround in reporting and acted upon. Much appreciated.

A very tiny remark -- `Dismiss()` is awaited and was wondering if `DismissAsync()` is a better name. It's one of those naming changes like the recent 'IsCancelable` but should be easy to do under the *alpha* tag.
Thanks again.

**Comment by paulvarache** [comment]
I had just the same idea for `Show` and `Dismiss` I'll probably rename them in the next update. I just want to make sure the returned `Task` completes when the animation finishes either on Show or Dismiss so that it can be used to schedule UI animations
