### ISSUE TITLE
Request for Enhancement: Can the Handle Bar Color be Settable?

### ISSUE THREAD

**Issue by dg2k** [the49code/The49.Maui.BottomSheet#20]
The little Handler Bar at the top (when `HasHandle = true`) almost disappears with dark background setting (and, of course, disappears completely if same background color is set).

To set a contrasting Handle color to a chosen sheet background color, can a `HandleColor` property be provided such that it can be set in XAML or via binding?

**Comment by paulvarache** [comment]
I think this makes sense. I looked into it before and it seems to be a bit tricky on iOS, but maybe doable. I'll leave this issue open as a tracker for this feature

**Comment by paulvarache** [comment]
Leaving this here for reference:
iOS:
https://stackoverflow.com/questions/71974578/how-to-make-uisheetpresentationcontroller-prefersgrabbervisible-follow-light-dar
Android:
`handle.SetColorFilter(Colors.Red.ToPlatform());`

**Comment by paulvarache** [comment]
Was added to rc1, Android only
