### ISSUE TITLE
Non-modal sheets not work while using NavigationPage

### ISSUE THREAD

**Issue by 1357310795** [the49code/The49.Maui.BottomSheet#3]
## Description
See title.

## Steps to Reproduce
1. Clone and open solution
2. In `App.xaml.cs`, replace `MainPage = new AppShell();` with `MainPage = new NavigationPage(new MainPage());`
3. Run and try to open a Non-modal sheet

## Version with bug
1.0.0-alpha1

## Affected platforms
Android

**Comment by 1357310795** [comment]
BTW, this package is incredibly awesome.👍👍👍 

Native bottom sheets is way more fluent and elegant than those implemented in xaml.(e.g. https://github.com/naweed/Maui.Controls.BottomSheet)

**Comment by paulvarache** [comment]
Thank you so much for the fix and the kind words. I have made another PR #5  based on yours to address one issue with your fix: In the case of using a `NavigationPage`, there was a `CoordinatorLayout` nested inside the existing one. It also created a small layout shift every time a non-modal sheet was opened.

This gave me an excuse to remove the android layout that was used. I wanted to remove that anyways.

I'll merge the new PR and close this one. I have not deleted your commit so you'll still be attributed a contribution.

Thanks again for showing an interest in this package and contributing
