### ISSUE TITLE
Input transparency

### ISSUE THREAD

**Issue by kissgyula** [the49code/The49.Maui.BottomSheet#6]
Is it possible to have input transparent backdrop with this?

**Comment by paulvarache** [comment]
Hi,

Setting `IsModal` to false will show a sheet with no backdrop on Android, the page behind the sheet can be interacted with. This follows the standard and modal behaviour of a [Material3 BottomSheet](https://m3.material.io/components/bottom-sheets/guidelines#d3146927-ad1b-49a3-9626-84cfa2890c52)
On iOS, we are bound to the rules of the [uisheetpresentationcontroller](uisheetpresentationcontroller), so I am unsure this is possible

**Comment by softlion** [comment]
I won't have rename IsModal to HasBackdrop. I just searched 10mn on how to make this dialog modal, as with the default value it is not, and trying to dismiss it using an android or ios integrated gesture (swipe left or swipe down) does not dismiss it. And also you can interact with the controls outside of the dialog, which is not expected by default.
