### ISSUE TITLE
Example using from a viewModel

### ISSUE THREAD

**Issue by developer9969** [the49code/The49.Maui.BottomSheet#7]
Hi it looks very nice..  Do you have an example how can you trigger a bottomsheet from a view model?

many thanks

**Comment by paulvarache** [comment]
This is not really related to this project specifically, but here's my take on what you are asking:

The only thing needed to open a bottom sheet is the window in which you want to open it to. With that in mind there are a few ways you can do that within your ViewModel:
 - Fire an event from your ViewModel, and let the page open the sheet (separates data and UI)
 - Pass the Window to your ViewModel when you instantiate it
 - If your app only has one window, use `Application.Current.Windows[0]` to get the window
 
Then it's just a question of instantiating you bottom sheet and calling `Show` with the window reference
