### ISSUE TITLE
Error : Java.Lang.IllegalArgumentException Message=ratio must be a float value between 0 and 1

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [the49code/The49.Maui.BottomSheet#9]
Hi,

I have tried this plugin. The first time I'm run Page.Show(), the BottomSheet shows successfully.

However, if I try a second time, it throws an error saying : 

    Java.Lang.IllegalArgumentException Message=ratio must be a float value between 0 and 1

Do you know please how to solve that ?

Thanks.

Regards,

**Comment by paulvarache** [comment]
Hi, thank you for opening this issue. This error comes from the Android SDK, it seems to indicate one of the detents (snap points) is outside the 0 - 1 range (0 and 1 excluded).

One possible reason behind that is if you use the `ContentDetent` (which is the default) and the sheet has no content or the content height is 0 at initialisation time, the ratio given to Android would be 0.

Could you share the whole stack trace here? This would help a lot in debugging this. If you have an isolated reproduction repo, even better.

**Comment by paulvarache** [comment]
More info, including a workaround is available in issue #11. Closing this one in favour of it
